name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.2.0"

      - name: Install dependencies
        run: |
          cd front-end/ecom-client
          npm install

      - name: Run lint
        run: |
          cd front-end/ecom-client
          npm run lint

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          cd back-end
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run lint
        run: |
          cd back-end
          . venv/bin/activate
          pylint *.py

      - name: Run tests
        run: |
          cd backend
          . venv/bin/activate
          pytest
